name: Deploy Spring Boot App to AWS EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn clean package

    # Nuevo paso unificado para subir y reiniciar
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USER }}
        SOURCE: "target/*.jar"
        TARGET: "/home/${{ secrets.EC2_USER }}"
        SCRIPT_AFTER: |
          echo "--- Reiniciando la aplicación en el servidor ---"
          PID=$(pgrep -f .jar)
          if [ -n "$PID" ]; then
            echo "Deteniendo proceso anterior con PID: $PID"
            kill -9 $PID
          fi
          cd /home/${{ secrets.EC2_USER }}
          echo "Iniciando nueva versión..."
          nohup java -Xmx1g -jar *.jar > app.log 2>&1 &
